# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_picshow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 663)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setViewportUpdateMode(QtWidgets.QGraphicsView.SmartViewportUpdate)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.horizontalWidget)
        self.label.setMaximumSize(QtCore.QSize(88, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.horizontalWidget)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 0.99)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox)
        self.verticalLayout.addWidget(self.horizontalWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout_3.addWidget(self.timeLabel)
        self.timeLine = QtWidgets.QSlider(self.centralwidget)
        self.timeLine.setPageStep(5)
        self.timeLine.setProperty("value", 0)
        self.timeLine.setOrientation(QtCore.Qt.Horizontal)
        self.timeLine.setTickInterval(19)
        self.timeLine.setObjectName("timeLine")
        self.horizontalLayout_3.addWidget(self.timeLine)
        self.frameBox = QtWidgets.QSpinBox(self.centralwidget)
        self.frameBox.setObjectName("frameBox")
        self.horizontalLayout_3.addWidget(self.frameBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lastSecond = QtWidgets.QPushButton(self.centralwidget)
        self.lastSecond.setMinimumSize(QtCore.QSize(0, 48))
        self.lastSecond.setCheckable(False)
        self.lastSecond.setObjectName("lastSecond")
        self.horizontalLayout.addWidget(self.lastSecond)
        self.last = QtWidgets.QPushButton(self.centralwidget)
        self.last.setMinimumSize(QtCore.QSize(0, 48))
        self.last.setObjectName("last")
        self.horizontalLayout.addWidget(self.last)
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setMinimumSize(QtCore.QSize(0, 48))
        self.next.setCheckable(False)
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        self.nextSecond = QtWidgets.QPushButton(self.centralwidget)
        self.nextSecond.setMinimumSize(QtCore.QSize(0, 48))
        self.nextSecond.setObjectName("nextSecond")
        self.horizontalLayout.addWidget(self.nextSecond)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 874, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menu_V = QtWidgets.QMenu(self.menuBar)
        self.menu_V.setObjectName("menu_V")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.action_H = QtWidgets.QAction(MainWindow)
        self.action_H.setObjectName("action_H")
        self.action_L = QtWidgets.QAction(MainWindow)
        self.action_L.setObjectName("action_L")
        self.action_J = QtWidgets.QAction(MainWindow)
        self.action_J.setObjectName("action_J")
        self.action_K = QtWidgets.QAction(MainWindow)
        self.action_K.setObjectName("action_K")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionStop)
        self.menu_V.addAction(self.action_H)
        self.menu_V.addAction(self.action_L)
        self.menu_V.addSeparator()
        self.menu_V.addAction(self.action_J)
        self.menu_V.addAction(self.action_K)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menu_V.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setToolTip(_translate("MainWindow", "每帧图片之间的相似程度不超过这个值，就保存"))
        self.label.setText(_translate("MainWindow", "相似度不高于："))
        self.timeLabel.setText(_translate("MainWindow", "00 | 00"))
        self.lastSecond.setText(_translate("MainWindow", "上一秒（&H)"))
        self.last.setText(_translate("MainWindow", "上一帧（&J）"))
        self.next.setText(_translate("MainWindow", "下一帧（&K）"))
        self.next.setShortcut(_translate("MainWindow", "Return"))
        self.nextSecond.setText(_translate("MainWindow", "下一秒(&L)"))
        self.menuFile.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_V.setTitle(_translate("MainWindow", "视频帧(&V)"))
        self.actionOpen.setText(_translate("MainWindow", "打开(&O)"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_H.setText(_translate("MainWindow", "上一秒(&H)"))
        self.action_H.setShortcut(_translate("MainWindow", "H"))
        self.action_L.setText(_translate("MainWindow", "下一秒(&L)"))
        self.action_L.setShortcut(_translate("MainWindow", "L"))
        self.action_J.setText(_translate("MainWindow", "上一帧(&J)"))
        self.action_J.setShortcut(_translate("MainWindow", "J"))
        self.action_K.setText(_translate("MainWindow", "下一帧(&K)"))
        self.action_K.setShortcut(_translate("MainWindow", "K"))
        self.actionSave.setText(_translate("MainWindow", "保存所有图片(&S)"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionStop.setText(_translate("MainWindow", "停止保存"))
        self.actionStop.setShortcut(_translate("MainWindow", "Ctrl+D"))
